//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalUi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PracticalUi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;openapi&quot;: &quot;3.0.1&quot;,
        ///  &quot;info&quot;: {
        ///    &quot;title&quot;: &quot;Handshake&quot;,
        ///    &quot;version&quot;: &quot;0.0.1&quot;
        ///  },
        ///  &quot;paths&quot;: {
        ///    &quot;/Post/getcloseposts&quot;: {
        ///      &quot;get&quot;: {
        ///        &quot;tags&quot;: [
        ///          &quot;Post&quot;
        ///        ],
        ///        &quot;summary&quot;: &quot;Gets all posts nearby.&quot;,
        ///        &quot;responses&quot;: {
        ///          &quot;200&quot;: {
        ///            &quot;description&quot;: &quot;Success&quot;
        ///          }
        ///        }
        ///      }
        ///    },
        ///    &quot;/Post&quot;: {
        ///      &quot;post&quot;: {
        ///        &quot;tags&quot;: [
        ///          &quot;Post&quot;
        ///        ],
        ///        &quot;summary&quot;: &quot;Posts a new post.&quot;,
        ///        &quot;reques [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntegerLesson {
            get {
                return ResourceManager.GetString("IntegerLesson", resourceCulture);
            }
        }
    }
}
